package roman.kononenko.busterminal.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import roman.kononenko.busterminal.entity.Stop;

import java.util.List;

@Repository
public interface StopRepository extends JpaRepository<Stop, Long> {

    //additional func, write myself
    @Query("from Stop s join s.address a where a.id = :id")
    List<Stop> findStopById(@Param("id") Long id);

    //Equal func, autogenerated by right name
    List<Stop> findAllByAddress_Id(Long id);
}
